---
- hosts: all 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy file from master to nodes
    copy: 
     src: mycopyfile
     dest: /home/maha/mycopyfile 
  - name: copy indexfile from master to nodes
    template: 
     src: myindexfile.j2
     dest: /var/www/html/index.html
    notify: restartwebserver
  - name: Download file and force basic auth
    get_url:
      url: http://example.com/path/file.conf
      dest: /etc/foo.conf
      force_basic_auth: yes
  handlers:
  -name: restart webserver
    service:
      name: apache2
      state: restarted