---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this task, i want to install apache2 webserver
    apt:
      name: apache2
      state: present
  - name: in this task, i want to start apache2 webserver
    service:
      name: apache2
      state: present
