---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: in this task, i want to install apache2 webserver
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian "  
  - name: in this task, i want to start apache2 webserver
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"
  - name: in this task, i want to install redhat2 webserver
    apt:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family== "redhat2" 
