---
- name: download tomcat tar file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/maha/apache-tomcat-10.0.20.tar.gz
    force_basic_auth: yes

- name: Create tomcat folder
  file:
    path: /opt/tomcat
    state: directory

- name: extract the tar file
  command:
    cmd: sudo tar xzvf /home/maha/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE